//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvictPowerSrv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvictPowerSrv.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got unexpected error when looking up events: {0}
        ///{1}.
        /// </summary>
        internal static string Loop_Log_CheckStatus_Error {
            get {
                return ResourceManager.GetString("Loop_Log_CheckStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Preempt event. {0} (Not until: {1}), by {2}..
        /// </summary>
        internal static string Loop_Log_CheckStatus_Preempt {
            get {
                return ResourceManager.GetString("Loop_Log_CheckStatus_Preempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got unexpected status {0}..
        /// </summary>
        internal static string Loop_Log_CheckStatus_Unexpected_HTTP_Code {
            get {
                return ResourceManager.GetString("Loop_Log_CheckStatus_Unexpected_HTTP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckStatus() returned an error. The service will retry periodically..
        /// </summary>
        internal static string Loop_Log_Error_CheckStatus {
            get {
                return ResourceManager.GetString("Loop_Log_Error_CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down the system immediately..
        /// </summary>
        internal static string Loop_Log_Shutdown {
            get {
                return ResourceManager.GetString("Loop_Log_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown the system properly before Azure evicts your Spot instance..
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down..
        /// </summary>
        internal static string Service_Log_Shutdown {
            get {
                return ResourceManager.GetString("Service_Log_Shutdown", resourceCulture);
            }
        }
    }
}
